requires 'AnyEvent';
requires 'DBD::SQLite';
requires 'DBI';
requires 'Digest::SHA1';
requires 'JSON::PP';
requires 'LWP::Protocol::https';
requires 'Mastodon::Client';
requires 'Mojolicious';
requires 'WWW::Telegram::BotAPI';
